name: CI

on:
  workflow_dispatch: # allows manual triggering
    inputs:
      create_release:
        description: "Create new release"
        required: true
        type: boolean
  push:
    paths: [".github/workflows/**", "Sources/**/*", "Package.swift", "llama.xcodeproj/**/*"]
  pull_request:
    paths: [".github/workflows/**", "Sources/**/*", "Package.swift", "llama.xcodeproj/**/*"]

jobs:
  swift-build:
    runs-on: macos-latest
    steps:
      - name: Clone repo
        id: checkout
        uses: actions/checkout@v1
      - name: Update dependencies
        id: depends
        run: |
          brew update
      - name: Swift build
        id: swift_build
        run: |
          swift build
